---
title: "Class Code"
output: html_notebook
---

# Demonstrate Quantmod

```{r package}

library(quantmod)
library(MTS)
library(tidyverse)
library(magrittr)
library(fGarch)
source("Corner.R")


```

```{r quantmod}

getSymbols("AMZN")
chartSeries(AMZN)
getSymbols("UNRATE", src = "FRED")
chartSeries(UNRATE)

```

```{r week 2}

set.seed(1069)
T2 <- 300
k2 <- 3
zt2 <- matrix(rnorm(T2*k2), T2, k2)

MTSplot(zt2)

ccm(zt2)

mq(zt2)

```

```{r week 3}

gasfur <- read_table("gasfur.txt")
colnames(gasfur) <- c("xt", "yt")
MTSplot(gasfur)
VARorder(gasfur)

# aic bic hq -> the lowest 
# sequential p -> see what is the last significant

gasfur_m <- VAR(gasfur, 6)
# the AR matrix and two s.d. estimate can give you a sense of which is significant

names(gasfur_m)
# phi as the coefficient of AR model
# Sigma as the 

MTSdiag(gasfur_m)
# the residual matrix of eveything

gasfur_mr <- refVAR(gasfur_m, thres = 1.5) 
# thres as t-ratio threshold
# see whether aic drops or rise...if drops, then that's good

gasfur_mpr <- VARpred(gasfur_mr, 4)
# prediction at four 

k1 <- VARpsi(gasfur_mr$Phi)
# calculate the MA psi representation

VARirf(gasfur_mr$Phi, gasfur_mr$Sigma, lag = 24)
# the plot tells you about the MA representation of two time series 
# 1,1, 2,2 => autoregression, 
# 2,1 => second series as input , first as response (no effect, indicating Granger)
# first plot is the everystep impact
# second plot is the accumulative impact

VARchi(gasfur, p =6)
# reconfirm the threshold and zero is okay

GrangerTest(gasfur, p = 6, locInput = c(1))
# the p value here is to see whether to put zero on the first six lag of [1,2] element is plausible
# the null hypo is all lag p of 1,2 equals zero
# what we want to find is a high p, not to reject the null



```


```{r week 4}

da4 <- read.table("m-dec5n8-6116.txt", skip = 1)
zt4 <- select(da4, V2, V3)
MTSplot(zt4)
VMAorder(zt4, lag = 20) # the Q(m) statistics will tell you which is the right order 

da4_1 <- read.table("flourc.txt")
Eccm(da4_1) # see the p value, search for the large ones

## Important note in diagnosis, the most important is to have a large p value, for you want the residual to be scattered
## VARMAirf (impulse response function)


# demonstration of unit root problem
set.seed(1069)
at_4 <- rnorm(1000)
acf(at_4)
Box.test(at_4)

bt_4 <- rnorm(1000)
y <- cumsum(at_4)
x <- cumsum(bt_4)

m4_1 <- lm(y~x)
summary(m4_1) 
## the two is independent but the p-value is high. It's because of the t-distribution is wrongly selected

```


```{r week 7}

da7 <- read.table("m-hsoldhst6312.txt", header = TRUE)
zt7 <- da7[,c(3,4)]


```

```{r week 9}

garchFit
volatility
ts.plot



```



